name: termina_clock
description: "Termina Clock is a Flutter package that provides a customizable clock widget inspired by the Termina clock from The Legend of Zelda - Majora's Mask"
version: 0.0.1
homepage: https://github.com/zonaro/termina_clock

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/termina_clock/center.png
    - assets/termina_clock/day_indicator.png
    - assets/termina_clock/night_indicator.png
    - assets/termina_clock/minutes_disc.png
    - assets/termina_clock/hours_disc.png
    
  
